version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: qsp_redis
    networks:
      - qsp_network

  backend:
    build: ./backend
    container_name: qsp_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/apps:/app/apps
      - ./backend/config:/app/config
      - ./backend/scripts:/app/scripts
      - ./backend/manage.py:/app/manage.py
      - ./backend/.env.dev:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - redis
    networks:
      - qsp_network

  frontend:
    build: ./frontend
    container_name: qsp_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - qsp_network

  celery_worker:
    build: ./backend
    container_name: qsp_celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend/apps:/app/apps
      - ./backend/config:/app/config
      - ./backend/manage.py:/app/manage.py
      - ./backend/.env.dev:/app/.env
    env_file:
      - ./backend/.env.dev
    depends_on:
      - redis
      - backend
    networks:
      - qsp_network

networks:
  qsp_network:
    driver: bridge
